//! Placeholder build.rs — generates the schema types at compile time.
//!
//! Phase 1 Step 4 will replace this with the full codegen that reads `schema.json`
//! and produces the Node/Edge enums, data structs, ref structs, and Schema metadata.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");
    let dest_path = Path::new(&out_dir).join("generated_schema.rs");

    // Placeholder: emit a minimal schema module so the build succeeds.
    // In Step 4 this will be replaced with real codegen from schema.json.
    let code = r#"
// This file is generated by build.rs from schema.json.
// Placeholder — will be replaced with real codegen in Phase 1, Step 4.

/// Placeholder for the Node enum.
pub enum Node {}
/// Placeholder for the Edge enum.
pub enum Edge {}
/// Placeholder for Schema metadata.
pub struct Schema {}
"#;

    fs::write(&dest_path, code).expect("Failed to write generated_schema.rs");
    println!("cargo::rerun-if-changed=build.rs");
}
