//! Build script — reads `schema-5.2.json` (and other versioned schema files) and generates Rust
//! types at compile time.
//!
//! # How it works
//!
//! 1. Locates `schema-5.2.json` relative to the workspace root (via `CARGO_MANIFEST_DIR`).
//! 2. Parses the JSON schema.
//! 3. Generates Rust source code to `$OUT_DIR/generated_schema.rs`:
//!    - `Node` enum — one variant per primary type
//!    - `Edge` enum — one variant per edge kind (handle refs, embedded refs, mixins)
//!    - Data structs per primary type (`PersonData`, `FamilyData`, …)
//!    - Secondary/embedded structs (`EventRef`, `ChildRef`, …)
//!    - Enum types (`EventType`, `EventRoleType`, …)
//!    - `Schema` runtime metadata struct

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=../../schemas/schema-5.2.json");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo");
    let crate_dir = Path::new(&manifest_dir);
    let workspace_root = crate_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("crate is two levels deep in workspace");
    let schema_path = workspace_root.join("schemas/schema-5.2.json");

    let schema_json = match fs::read_to_string(&schema_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "error: failed to read schema.json at {}: {}",
                schema_path.display(),
                e
            );
            eprintln!("  hint: ensure schema-5.2.json exists at schemas/schema-5.2.json");
            std::process::exit(1);
        }
    };

    let schema: serde_json::Value = match serde_json::from_str(&schema_json) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("error: failed to parse schema file: {}", e);
            std::process::exit(1);
        }
    };

    let code = generate_code(&schema);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");
    let dest_path = Path::new(&out_dir).join("generated_schema.rs");
    fs::write(&dest_path, &code).expect("Failed to write generated_schema.rs");
}

fn generate_code(schema: &serde_json::Value) -> String {
    let mut code = String::new();

    code.push_str("// This file is @generated by build.rs from schema-5.2.json.\n");
    code.push_str("// Do not edit manually — edit schema-5.2.json and rebuild.\n\n");
    code.push_str("use std::collections::HashMap;\n\n");
    code.push_str("/// Handle uniquely identifies a primary object in the graph.\n");
    code.push_str("/// Matches Gramps' own handle semantics (UUID v4 string, 36 chars).\n");
    code.push_str("pub type Handle = String;\n\n");

    // 1. Generate enum types
    generate_enum_types(&mut code, schema);

    // 2. Generate secondary (embedded) ref types
    generate_secondary_types(&mut code, schema);

    // 3. Generate primary type data structs
    let primary_types = get_sorted_primary_types(schema);
    generate_data_structs(&mut code, &primary_types);

    // 4. Generate Node enum
    generate_node_enum(&mut code, &primary_types);

    // 5. Generate Edge enum
    generate_edge_enum(&mut code, &primary_types, schema);

    // 6. Generate Schema metadata
    generate_schema_metadata(&mut code, &primary_types, schema);

    code
}

fn get_sorted_primary_types(schema: &serde_json::Value) -> Vec<(String, &serde_json::Value)> {
    let mut pairs: Vec<(String, &serde_json::Value)> = Vec::new();
    if let Some(obj) = schema.get("primary_types").and_then(|v| v.as_object()) {
        for (k, v) in obj {
            pairs.push((k.clone(), v));
        }
        pairs.sort_by(|a, b| a.0.cmp(&b.0));
    }
    pairs
}

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

fn generate_enum_types(code: &mut String, schema: &serde_json::Value) {
    let Some(enum_types) = schema.get("enum_types").and_then(|v| v.as_object()) else {
        return;
    };

    code.push_str("// ---- Generated enum types ----\n\n");

    let mut names: Vec<&str> = enum_types.keys().map(|k| k.as_str()).collect();
    names.sort();

    for name in &names {
        let info = &enum_types[*name];
        let enum_name = to_pascal_case(name);
        let values = info
            .get("values")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| {
                        v.as_str()
                            .map(|s| s.to_string())
                            .or_else(|| v.as_i64().map(|n| n.to_string()))
                    })
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        code.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]\n");
        code.push_str(&format!("pub enum {} {{\n", enum_name));

        let mut unique: Vec<String> = values.clone();
        unique.sort();
        unique.dedup();

        for (i, value) in unique.iter().enumerate() {
            let variant = to_enum_variant_name(value);
            if i == 0 {
                code.push_str(&format!(
                    "    /// {} value.\n    #[default]\n    {},\n",
                    value, variant
                ));
            } else {
                code.push_str(&format!("    /// {} value.\n    {},\n", value, variant));
            }
        }
        code.push_str("}\n\n");
    }
}

// ---------------------------------------------------------------------------
// Secondary types
// ---------------------------------------------------------------------------

fn generate_secondary_types(code: &mut String, schema: &serde_json::Value) {
    let Some(secondary_types) = schema.get("secondary_types").and_then(|v| v.as_object()) else {
        return;
    };

    code.push_str("// ---- Generated secondary/embedded types ----\n\n");

    let mut names: Vec<&str> = secondary_types.keys().map(|k| k.as_str()).collect();
    names.sort();

    for name in &names {
        let info = &secondary_types[*name];
        let struct_name = to_pascal_case(name);
        let fields = info.get("fields").and_then(|v| v.as_object());
        gen_struct_from_fields(code, &struct_name, fields);
    }
}

// ---------------------------------------------------------------------------
// Data structs
// ---------------------------------------------------------------------------

fn generate_data_structs(code: &mut String, primary_types: &[(String, &serde_json::Value)]) {
    code.push_str("// ---- Generated primary type data structs ----\n\n");

    for (name, info) in primary_types {
        let struct_name = format!("{}Data", to_pascal_case(name));
        let fields = info.get("fields").and_then(|v| v.as_object());
        gen_struct_from_fields(code, &struct_name, fields);
    }
}

// ---------------------------------------------------------------------------
// Node enum
// ---------------------------------------------------------------------------

fn generate_node_enum(code: &mut String, primary_types: &[(String, &serde_json::Value)]) {
    code.push_str("// ---- Generated Node enum ----\n\n");
    code.push_str("/// Enum over all primary node types.\n");
    code.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    code.push_str("pub enum Node {\n");

    for (name, _) in primary_types {
        let type_name = to_pascal_case(name);
        let struct_name = format!("{}Data", type_name);
        code.push_str(&format!(
            "    /// {} node variant.\n    {}({}),\n",
            name, type_name, struct_name
        ));
    }

    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Edge enum
// ---------------------------------------------------------------------------

fn generate_edge_enum(
    code: &mut String,
    primary_types: &[(String, &serde_json::Value)],
    schema: &serde_json::Value,
) {
    code.push_str("// ---- Generated Edge enum ----\n\n");
    code.push_str("/// Enum over all edge kinds in the typed graph.\n");
    code.push_str("/// Each variant carries the source and target handle.\n");
    code.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    code.push_str("pub enum Edge {\n");

    let mut edge_variants: Vec<String> = Vec::new();

    for (name, info) in primary_types {
        let source_type = to_pascal_case(name);
        let fields = info.get("fields").and_then(|v| v.as_object());
        let mixins = info
            .get("inherit_mixins")
            .and_then(|v| v.as_array())
            .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>())
            .unwrap_or_default();

        if let Some(fields) = fields {
            // Sort field names for deterministic output
            let mut field_names: Vec<&str> = fields.keys().map(|k| k.as_str()).collect();
            field_names.sort();

            for field_name in &field_names {
                let field_info = &fields[*field_name];

                // Check items-level structure first (for array fields)
                if let Some(items) = field_info.get("items").and_then(|v| v.as_object()) {
                    let items_kind = items.get("kind").and_then(|v| v.as_str());
                    let items_target = items.get("target").and_then(|v| v.as_str());

                    // Array items with kind: handle_ref (e.g., family_list, note_list)
                    if items_kind == Some("handle_ref") {
                        if let Some(target_type) = items_target {
                            let edge_name = format!(
                                "{}{}",
                                source_type,
                                to_pascal_case(strip_handle_suffix(field_name))
                            );
                            edge_variants.push(format!(
                                "    /// {} → {} via {}.\n    {} {{ source: Handle, target: Handle }},",
                                name, target_type, field_name, edge_name
                            ));
                        }
                        continue;
                    }

                    // Embedded ref items with edges (e.g., event_ref_list, child_ref_list)
                    if let Some(embedded_name) = items.get("embedded").and_then(|v| v.as_str()) {
                        if let Some(edges) = items.get("edges").and_then(|v| v.as_array()) {
                            for edge in edges {
                                if let (Some(link), Some(edge_target)) = (
                                    edge.get("link").and_then(|v| v.as_str()),
                                    edge.get("target").and_then(|v| v.as_str()),
                                ) {
                                    let ref_type = link.split('.').next().unwrap_or(embedded_name);
                                    let edge_name =
                                        format!("{}{}", source_type, to_pascal_case(ref_type));
                                    let has_meta = has_ref_metadata(embedded_name, schema);
                                    if has_meta {
                                        let meta_type = to_pascal_case(ref_type);
                                        edge_variants.push(format!(
                                            "    /// {} → {} via {}.\n    {} {{ source: Handle, target: Handle, metadata: Box<{}> }},",
                                            name, edge_target, field_name, edge_name, meta_type
                                        ));
                                    } else {
                                        edge_variants.push(format!(
                                            "    /// {} → {} via {}.\n    {} {{ source: Handle, target: Handle }},",
                                            name, edge_target, field_name, edge_name
                                        ));
                                    }
                                }
                            }
                        }
                        continue;
                    }
                }

                // Top-level handle_ref fields (direct handle values, not arrays)
                let kind = field_info.get("kind").and_then(|v| v.as_str());
                let target = field_info.get("target").and_then(|v| v.as_str());

                if kind == Some("handle_ref") {
                    if let Some(target_type) = target {
                        let edge_name = format!(
                            "{}{}",
                            source_type,
                            to_pascal_case(strip_handle_suffix(field_name))
                        );
                        edge_variants.push(format!(
                            "    /// {} → {} via {}.\n    {} {{ source: Handle, target: Handle }},",
                            name, target_type, field_name, edge_name
                        ));
                    }
                }
            }
        }

        // Mixin edges
        for mixin in &mixins {
            if let Some(variant) = gen_mixin_edge(name, source_type.as_str(), mixin) {
                edge_variants.push(variant);
            }
        }
    }

    // Deduplicate edge variants by their actual variant name (text after the last doc comment, before '{')
    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for variant in &edge_variants {
        // Extract the variant name: take the last line, split on whitespace, find the name before '{'
        let last_line = variant.lines().last().unwrap_or("");
        let name_part = last_line.split('{').next().unwrap_or("").trim();
        if seen.insert(name_part.to_string()) {
            code.push_str(variant);
            code.push('\n');
        }
    }

    code.push_str("}\n\n");
}

/// Check if a ref type has metadata fields beyond `ref`.
fn has_ref_metadata(embedded_name: &str, schema: &serde_json::Value) -> bool {
    let Some(secondary) = schema.get("secondary_types").and_then(|v| v.as_object()) else {
        return false;
    };
    let Some(info) = secondary.get(embedded_name) else {
        return false;
    };
    let Some(fields) = info.get("fields").and_then(|v| v.as_object()) else {
        return false;
    };
    fields.len() > 1 || !fields.contains_key("ref")
}

/// Generate an Edge variant for a mixin.
fn gen_mixin_edge(primary_type: &str, _source_type: &str, mixin: &str) -> Option<String> {
    match mixin {
        "CitationBase" => Some(format!(
            "    /// {} → Citation via citation_list.\n    CitationRef {{ source: Handle, target: Handle }},",
            primary_type
        )),
        "NoteBase" => Some(format!(
            "    /// {} → Note via note_list.\n    NoteRef {{ source: Handle, target: Handle }},",
            primary_type
        )),
        "MediaBase" => Some(format!(
            "    /// {} → Media via media_list.\n    MediaRef {{ source: Handle, target: Handle }},",
            primary_type
        )),
        "TagBase" => Some(format!(
            "    /// {} → Tag via tag_list.\n    TagRef {{ source: Handle, target: Handle }},",
            primary_type
        )),
        _ => None,
    }
}

/// Strip `_handle` or `_list` suffix from a field name.
fn strip_handle_suffix(name: &str) -> &str {
    if let Some(stripped) = name.strip_suffix("_handle") {
        stripped
    } else if let Some(stripped) = name.strip_suffix("_list") {
        stripped
    } else {
        name
    }
}

// ---------------------------------------------------------------------------
// Schema metadata
// ---------------------------------------------------------------------------

fn generate_schema_metadata(
    code: &mut String,
    primary_types: &[(String, &serde_json::Value)],
    schema: &serde_json::Value,
) {
    code.push_str("// ---- Generated Schema metadata ----\n\n");
    code.push_str("/// Runtime metadata about the schema, for use by generators and validators.\n");
    code.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    code.push_str("pub struct Schema {\n");
    code.push_str("    /// Gramps version this schema was extracted from.\n");
    code.push_str("    pub version: &'static str,\n");
    code.push_str("    /// Required fields for each primary type.\n");
    code.push_str("    pub required_fields: HashMap<&'static str, Vec<&'static str>>,\n");
    code.push_str("    /// Cardinality constraints for each field: (field_key, (min, max)).\n");
    code.push_str(
        "    pub cardinality_constraints: HashMap<&'static str, (Option<u32>, Option<u32>)>,\n",
    );
    code.push_str("}\n\n");

    code.push_str("impl Schema {\n");
    code.push_str("    /// Create a Schema instance with metadata from the extracted schema.\n");
    code.push_str("    pub fn new() -> Self {\n");
    code.push_str("        let mut required_fields: HashMap<&'static str, Vec<&'static str>> = HashMap::new();\n");
    code.push_str("        let mut cardinality_constraints: HashMap<&'static str, (Option<u32>, Option<u32>)> = HashMap::new();\n");

    for (name, info) in primary_types {
        if let Some(fields) = info.get("fields").and_then(|v| v.as_object()) {
            let mut required: Vec<&str> = Vec::new();
            for (field_name, field_info) in fields {
                if field_info
                    .get("required")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false)
                {
                    required.push(field_name);
                }
                if let Some(cardinality) = field_info.get("cardinality").and_then(|v| v.as_object())
                {
                    let min = cardinality
                        .get("min")
                        .and_then(|v| v.as_i64())
                        .map(|v| v as u32);
                    let max = cardinality.get("max").and_then(|v| {
                        if v.is_null() {
                            None
                        } else {
                            v.as_i64().map(|v| v as u32)
                        }
                    });
                    let key = format!("{}.{}", name, field_name);
                    code.push_str(&format!(
                        "        cardinality_constraints.insert(\"{}\", ({:?}, {:?}));\n",
                        key, min, max
                    ));
                }
            }
            if !required.is_empty() {
                code.push_str(&format!(
                    "        required_fields.insert(\"{}\", vec!{:?});\n",
                    name, required
                ));
            }
        }
    }

    let version = schema
        .get("version")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");
    code.push_str("        Self {\n");
    code.push_str(&format!("            version: \"{}\",\n", version));
    code.push_str("            required_fields,\n");
    code.push_str("            cardinality_constraints,\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("impl Default for Schema {\n");
    code.push_str("    fn default() -> Self {\n");
    code.push_str("        Self::new()\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Struct generation from schema fields
// ---------------------------------------------------------------------------

fn gen_struct_from_fields(
    code: &mut String,
    struct_name: &str,
    fields: Option<&serde_json::Map<String, serde_json::Value>>,
) {
    code.push_str("#[derive(Clone, Debug, PartialEq, Default)]\n");
    code.push_str(&format!("pub struct {} {{\n", struct_name));

    if let Some(fields) = fields {
        let mut field_names: Vec<&str> = fields.keys().map(|k| k.as_str()).collect();
        field_names.sort();

        for field_name in &field_names {
            let field_info = &fields[*field_name];
            let rust_field = to_snake_case(field_name);
            let rust_type = field_to_rust_type(field_info);
            code.push_str(&format!("    pub {}: {},\n", rust_field, rust_type));
        }
    }

    code.push_str("}\n\n");
}

/// Map a schema field info to its Rust type.
fn field_to_rust_type(field_info: &serde_json::Value) -> String {
    let field_type = field_info
        .get("type")
        .and_then(|v| v.as_str())
        .unwrap_or("string");
    let kind = field_info.get("kind").and_then(|v| v.as_str());
    let target = field_info.get("target").and_then(|v| v.as_str());
    let required = field_info
        .get("required")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    // Handle handle or handle_ref -> Handle or Option<Handle>
    if let Some(k) = kind {
        if k == "handle" || k == "handle_ref" {
            if required {
                return "Handle".to_string();
            } else {
                return "Option<Handle>".to_string();
            }
        }
    }

    match field_type {
        "string" => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "integer" => {
            if required {
                "i32".to_string()
            } else {
                "Option<i32>".to_string()
            }
        }
        "boolean" => {
            if required {
                "bool".to_string()
            } else {
                "Option<bool>".to_string()
            }
        }
        "enum" => {
            // Inline enum — use i32
            if required {
                "i32".to_string()
            } else {
                "Option<i32>".to_string()
            }
        }
        "enum_ref" => {
            if let Some(t) = target {
                let enum_name = to_pascal_case(t);
                if required {
                    enum_name
                } else {
                    format!("Option<{}>", enum_name)
                }
            } else if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "embedded" => {
            if let Some(schema_name) = field_info.get("schema").and_then(|v| v.as_str()) {
                let struct_name = to_pascal_case(schema_name);
                if required {
                    struct_name
                } else {
                    format!("Option<{}>", struct_name)
                }
            } else if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "array" => {
            let item_type = resolve_array_item_type(field_info);
            format!("Vec<{}>", item_type)
        }
        _ => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
    }
}

/// Resolve the item type for an array field.
fn resolve_array_item_type(field_info: &serde_json::Value) -> String {
    let items = field_info.get("items");
    let items = match items {
        Some(v) => v,
        None => return "String".to_string(),
    };

    if let Some(s) = items.as_str() {
        return to_pascal_case(s);
    }

    if let Some(obj) = items.as_object() {
        if let Some(embedded) = obj.get("embedded").and_then(|v| v.as_str()) {
            return to_pascal_case(embedded);
        }
        if let Some(kind) = obj.get("kind").and_then(|v| v.as_str()) {
            if kind == "handle_ref" {
                return "Handle".to_string();
            }
        }
    }

    "String".to_string()
}

// ---------------------------------------------------------------------------
// Name conversion helpers
// ---------------------------------------------------------------------------

/// Convert a name to PascalCase.
fn to_pascal_case(name: &str) -> String {
    if name.is_empty() {
        return "Unknown".to_string();
    }
    let mut result = String::new();
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '.' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            result.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

/// Convert a name to snake_case.
fn to_snake_case(name: &str) -> String {
    if name.is_empty() {
        return "unknown".to_string();
    }
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            result.push('_');
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch.to_ascii_lowercase());
        }
    }
    // Handle Rust keywords
    match result.as_str() {
        "type" => "type_field".to_string(),
        "ref" => "ref_field".to_string(),
        "self" => "self_field".to_string(),
        "match" => "match_field".to_string(),
        _ => result,
    }
}

/// Convert a string value to a Rust enum variant name.
fn to_enum_variant_name(value: &str) -> String {
    if value.is_empty() {
        return "Empty".to_string();
    }
    let sanitized: String = value
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                ' '
            }
        })
        .collect();

    let mut result = String::new();
    let mut upper_next = true;
    for ch in sanitized.chars() {
        if ch == ' ' || ch == '_' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            result.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else {
            result.push(ch);
        }
    }

    if result.is_empty() {
        return "Unknown".to_string();
    }
    if result
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        result.insert(0, '_');
    }
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("Person"), "Person");
        assert_eq!(to_pascal_case("event_ref"), "EventRef");
        assert_eq!(to_pascal_case("EventRef.ref"), "EventRefRef");
        assert_eq!(to_pascal_case(""), "Unknown");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("handle"), "handle");
        assert_eq!(to_snake_case("gramps_id"), "gramps_id");
        assert_eq!(to_snake_case("event_ref_list"), "event_ref_list");
        assert_eq!(to_snake_case("type"), "type_field");
        assert_eq!(to_snake_case("ref"), "ref_field");
    }

    #[test]
    fn test_to_enum_variant_name() {
        assert_eq!(to_enum_variant_name("Birth"), "Birth");
        assert_eq!(to_enum_variant_name("Also Known As"), "AlsoKnownAs");
        assert_eq!(to_enum_variant_name("Military Service"), "MilitaryService");
        assert_eq!(to_enum_variant_name(""), "Empty");
    }

    #[test]
    fn test_strip_handle_suffix() {
        assert_eq!(strip_handle_suffix("father_handle"), "father");
        assert_eq!(strip_handle_suffix("family_list"), "family");
        assert_eq!(strip_handle_suffix("handle"), "handle");
        assert_eq!(strip_handle_suffix("gramps_id"), "gramps_id");
    }
}
