[package]
name = "gramps-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1"
log = "0.4"
quick-xml = { workspace = true }
serde = { workspace = true }
typed-graph = { path = "../typed-graph" }

[dev-dependencies]
tempfile = "3"
output = { path = "../output" }
serde_json = { workspace = true }
rand = { workspace = true }
delete = { path = "../delete" }
