//! Schema types — generated by build.rs at compile time.
//!
//! This module reads the code-generated types from the build output directory.
//! The actual type definitions are produced by `build.rs` from `schema-5.2.json`.

// Build-time generated code from `build.rs` lives in `$OUT_DIR/generated_schema.rs`.
include!(concat!(env!("OUT_DIR"), "/generated_schema.rs"));
